on: [push, pull_request]

jobs:
  test:
    name: BorgBackup-FUSE test on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install required macFUSE
        run: brew install --cask osxfuse

      - name: Debug
        uses: mxschmitt/action-tmate@v3

      - name: Test formula
        working-directory: ./Formula
        run: |
          # brew audit --strict borgbackup-fuse.rb
          brew test borgbackup-fuse.rb

