on: [push, pull_request]

jobs:
  test:
    name: Test Homebrew install
    runs-on: macos-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install required macFUSE
        run: brew install --cask osxfuse

      - name: Debug
        uses: mxschmitt/action-tmate@v3

      - name: Test formula
        working-directory: ./Formula
        run: |
          #brew audit --strict borgbackup-fuse.rb
          brew install borgbackup-fuse.rb
          brew test borgbackup-fuse.rb

